/**
 * NFC APDU protocol shared by the host reader, the student HCE service and the backend.
 * The Kotlin modules mirror these constants; keep them in sync
 * (apps/host/modules/nfc-reader, apps/student/modules/attendance-hce).
 * Spec: docs/IDENTITY_AND_AUTH.md §2–3.
 */

/** Proprietary AID: F0 + ASCII "ATTEND". */
export const AID_HEX = "F0415454454E44";
export const PROTOCOL_VERSION = 1;

export const CLA_PROPRIETARY = 0x80;
export const INS_AUTH = 0x10;
export const INS_CONFIRM = 0x20;

export const Purpose = {
  ENROLL: 0x01,
  ATTEND: 0x02,
} as const;
export type PurposeName = keyof typeof Purpose;

/** P1 of the CONFIRM command: the verdict shown on the student phone. */
export const ConfirmResult = {
  PRESENT: 0x00,
  LATE: 0x01,
  ALREADY_MARKED: 0x02,
  ENROLLED: 0x03,
  NOT_ENROLLED: 0x10,
  OUTSIDE_WINDOW: 0x11,
  BAD_SIGNATURE: 0x12,
  UNKNOWN_DEVICE: 0x13,
} as const;

export const StatusWord = {
  OK: 0x9000,
  WRONG_LENGTH: 0x6700,
  NOT_REGISTERED: 0x6985,
  WRONG_P1: 0x6a86,
  INS_NOT_SUPPORTED: 0x6d00,
  SIGNING_FAILED: 0x6f00,
} as const;

export const NFC_TAG = "ATTv1-NFC";
export const LOGIN_TAG = "ATTv1-LOGIN";

const encoder = new TextEncoder();

export function uuidToBytes(uuid: string): Uint8Array {
  const hex = uuid.replace(/-/g, "");
  if (!/^[0-9a-fA-F]{32}$/.test(hex)) throw new Error(`Invalid UUID: ${uuid}`);
  const out = new Uint8Array(16);
  for (let i = 0; i < 16; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

export function bytesToUuid(bytes: Uint8Array): string {
  if (bytes.length !== 16) throw new Error("UUID must be 16 bytes");
  const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

function concat(parts: Uint8Array[]): Uint8Array {
  const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0));
  let offset = 0;
  for (const p of parts) {
    out.set(p, offset);
    offset += p.length;
  }
  return out;
}

function int64BE(value: number | bigint): Uint8Array {
  const out = new Uint8Array(8);
  new DataView(out.buffer).setBigInt64(0, BigInt(value), false);
  return out;
}

export interface NfcProofFields {
  purpose: PurposeName;
  /** classId for ENROLL, sessionId for ATTEND. */
  contextId: string;
  /** 16 random bytes generated by the host for this tap. */
  nonce: Uint8Array;
  /** Host clock, unix milliseconds. */
  hostTime: number | bigint;
  deviceId: string;
}

/** "ATTv1-NFC" || purpose(1) || contextId(16) || nonce(16) || hostTime(8, BE) || deviceId(16) */
export function buildNfcProofMessage(f: NfcProofFields): Uint8Array {
  if (f.nonce.length !== 16) throw new Error("NFC nonce must be 16 bytes");
  return concat([
    encoder.encode(NFC_TAG),
    Uint8Array.of(Purpose[f.purpose]),
    uuidToBytes(f.contextId),
    f.nonce,
    int64BE(f.hostTime),
    uuidToBytes(f.deviceId),
  ]);
}

/** "ATTv1-LOGIN" || deviceId(16) || serverNonce(32) */
export function buildLoginMessage(deviceId: string, nonce: Uint8Array): Uint8Array {
  if (nonce.length !== 32) throw new Error("Login nonce must be 32 bytes");
  return concat([encoder.encode(LOGIN_TAG), uuidToBytes(deviceId), nonce]);
}
